; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:disco_f303vc]
platform = ststm32
board = disco_f303vc
framework = arduino
board_microros_distro = humble
board_microros_transport = serial
build_flags =
    -D USBD_USE_CDC
    -D USBCON
    -I .pio/libdeps/disco_f303vc/micro_ros_platformio/libmicroros/include
    -L .pio/libdeps/disco_f303vc/micro_ros_platformio/libmicroros
    -l microros
lib_deps = 
    https://github.com/micro-ROS/micro_ros_platformio